### ISSUE TITLE
The tests are failing

### ISSUE THREAD

**Issue by xgalen** [alexfernandez/basic-request#4]
Hi Álex,

The tests of the projects are failing due to:

```
basic-request/test.js:62
	const url = 'http://httpbin.org/redirect-to?url=http%3A%2F%2Fhttpbin.org%2Fpo
	^^^^^
SyntaxError: Use of const in strict mode.
```

The `const` and `let` are part of ECMAScript 2015 (a.k.a. ES6 and Harmony), and was not enabled by default in Node.js 0.10 or 0.12. [source](https://stackoverflow.com/questions/22603078/syntaxerror-use-of-const-in-strict-mode)

I think two ways to solve this. I can send a PR after you choose:

a) Remove the `const`.
b) Include the `--harmony` param [here](https://github.com/alexfernandez/basic-request/blob/master/package.json#L32) and put a warn in the `README` about.
c) Upgrade the required version of `node` from `0.10.3` to `4.x`.

Maybe this could be the reason why the project is not being published on `npm`.

Cheers :D

**Comment by alexfernandez** [comment]
Oops, changed now! Thanks :smile:

**Comment by alexfernandez** [comment]
[Tests](https://travis-ci.org/alexfernandez/basic-request) are green again :green_heart:

Closing.
